### ISSUE TITLE
ROSCA creation: retain emails when changing the number of participants

### ISSUE THREAD

**Issue by rmerom** [WeTrustPlatform/rosca-mvp#24]
**To reproduce:**
1. Get to the Create ROSCA screen
2. Enter 3 in the # of participants field.
3. Enter a couple of emails.
4. Change # of participants to 4.

**Actual behavior:**
Already-entered emails are erased.

**Expected Behavior**
Already-entered emails are retained.

**Comment by morelazers** [comment]
#30
